backend:
  name: git-gateway
  branch: main

media_folder: "images/cakes"
public_folder: "/images/cakes"

collections:
  - name: "cake_data"
    label: "Cakes Menu"
    files:
      - name: "cakes_list"
        label: "Cake List"
        file: "content/cakes/index.json"
        fields:
          - name: "cakes"
            label: "Cakes"
            widget: "list"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Price", name: "price", widget: "string"}
              - {label: "Description", name: "description", widget: "text", required: false}
              - {label: "Cake Image", name: "image", widget: "image"}
